plugins {
    id 'java'
    id 'io.qameta.allure' version '4.1.0'
}

allure {
    report {
        version.set("2.19.0")
    }
    adapter { // отвечает за появление папочки build/allure-results
        aspectjWeaver.set(true) //обработка аннотации @Step
        frameworks {
            junit5 { //название фреймворка
                adapterVersion.set("2.19.0") //версия интеграции фреймворка и Allure
            }
        }
    }
}

group 'org.example'
version '1.0-SNAPSHOT'


repositories {
    mavenCentral()
}



dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
    testImplementation 'com.codeborne:selenide:7.0.1'
    testImplementation 'io.qameta.allure:allure-selenide:2.19.0'



}

test {
    useJUnitPlatform()
}